name: Deploy Django Application

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 코드 가져오기
      uses: actions/checkout@v3

    - name: Debug SSH Connection
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        debug: true
        script: |
          echo "SSH 연결 테스트 중..."

    - name: Start SSH Agent and Add Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: EC2에 배포
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}       # EC2 IP 주소
        username: ${{ secrets.EC2_USER }}   # EC2 사용자 이름 (예: ubuntu)
        key: ${{ secrets.EC2_KEY }}         # EC2 개인 키
        script: |
          set -e  # 스크립트 실행 중 오류 발생 시 중단
          echo "EC2 배포 시작"
        
          # SSH 키 인증 확인
          echo "SSH 키 인증 테스트..."
          ssh -T git@github.com || echo "GitHub 인증 실패: SSH 키 확인 필요"
        
          # GitHub 리모트 설정 확인
          echo "Git 리모트 URL 확인 중..."
          git remote -v
          git remote set-url origin git@github.com:Makourse/Makourse_BE.git
        
          echo "GitHub에서 최신 코드 가져오는 중..."
          git fetch --all || echo "Git fetch 실패"
          git reset --hard origin/main || echo "Git reset 실패"
        
          echo "가상환경 설정 중..."
          if [ ! -d "/home/ubuntu/makourse_env" ]; then
            python3.12 -m venv /home/ubuntu/makourse_env
          fi
          source /home/ubuntu/makourse_env/bin/activate 
        
          echo "의존성 설치 중..."
          pip install --upgrade pip
          pip install -r /home/ubuntu/Makourse_BE/makourse/requirements.txt || echo "의존성 설치 실패"
        
          echo "마이그레이션 및 정적 파일 수집 중..."
          python manage.py migrate || echo "마이그레이션 실패"
          python manage.py collectstatic --noinput || echo "정적 파일 수집 실패"
        
          echo "서비스 재시작 중..."
          uwsgi --ini /home/ubuntu/Makourse_BE/makourse/uwsgi.ini || echo "uWSGI 재시작 실패"
          sudo systemctl restart nginx || echo "Nginx 재시작 실패"
        
          echo "배포 완료!"
